---
name: Math-GrahamFunction
version: 0.02000
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  Calculate the Graham's Function of a Natural 
  Number.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://svn.berlios.de/svnroot/repos/web-cpan/Math-GrahamFunction/trunk/modules/Math-GrahamFunction
requires:
  Class::Accessor: 0
  List::Util: 0
build_requires:
  Test::More: 0
provides:
  Math::GrahamFunction:
    file: lib/Math/GrahamFunction.pm
    version: 0.02000
  Math::GrahamFunction::Object:
    file: lib/Math/GrahamFunction/Object.pm
  Math::GrahamFunction::SqFacts:
    file: lib/Math/GrahamFunction/SqFacts.pm
  Math::GrahamFunction::SqFacts::Dipole:
    file: lib/Math/GrahamFunction/SqFacts/Dipole.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - factors
  - fun
  - function
  - graham
  - math
  - mathematics
  - maths
  - mjd
  - obscure
  - pure-perl
  - riddle
  - riddles
  - quizzes
  - qotw
  - quiz
  - quiz-of-the-week
  - square
  - week
